from __future__ import annotations

from pathlib import Path


def _as_float(value, default: float) -> float:
    try:
        return float(value)
    except Exception:
        return float(default)


def _as_int(value, default: int) -> int:
    try:
        return int(value)
    except Exception:
        return int(default)


def _normalize_direction(value) -> tuple[str, bool]:
    direction = str(value or "+z").strip().lower()
    if direction in {"x", "y", "z"}:
        return direction, False
    if direction in {"+x", "+y", "+z"}:
        return direction[1], False
    if direction in {"-x", "-y", "-z"}:
        return direction[1], True
    return "z", False


def _axis_lines(base_resolution: float, max_resolution: float) -> list[float]:
    step = max(float(base_resolution), 1e-9)
    max_step = max(float(max_resolution), step)
    half_span = max(max_step * 8.0, step * 12.0)
    pos = 0.0
    lines: list[float] = [0.0]

    while pos + step < half_span:
        pos += step
        lines.append(round(pos, 9))
        step = min(max_step, step * 1.3)

    mirrored = [-value for value in reversed(lines[1:])]
    return mirrored + lines


def _grid_lines_from_model(model) -> tuple[list[float], list[float], list[float], float]:
    grid = model.grid or {}
    sim = model.simulation or {}
    base = _as_float(grid.get("BaseResolution", 1.0), 1.0)
    max_res = _as_float(grid.get("MaxResolution", 5.0), 5.0)
    if max_res < base:
        max_res = base
    delta_unit = _as_float(sim.get("DeltaUnit", 1e-3), 1e-3)
    axis = _axis_lines(base, max_res)
    return axis, axis, axis, delta_unit


def _vec3(values, default: list[float]) -> list[float]:
    if not isinstance(values, (list, tuple)) or len(values) != 3:
        return [float(default[0]), float(default[1]), float(default[2])]
    return [
        _as_float(values[0], default[0]),
        _as_float(values[1], default[1]),
        _as_float(values[2], default[2]),
    ]


def _safe_symbol(value: str) -> str:
    text = str(value or "").strip()
    if not text:
        return "material"
    chars = []
    for ch in text:
        if ch.isalnum() or ch == "_":
            chars.append(ch)
        else:
            chars.append("_")
    symbol = "".join(chars)
    if symbol and symbol[0].isdigit():
        symbol = f"m_{symbol}"
    return symbol or "material"


def generate_openems_script(
    model,
    script_path: str | Path,
    runnable: bool = False,
    run_output_dir: str | Path | None = None,
) -> Path:
    path = Path(script_path)
    lines: list[str] = []
    if runnable:
        lines.append("# Auto-generated by OpenEMS FreeCAD Workbench (Phase 7 run-ready)")
    else:
        lines.append("# Auto-generated by OpenEMS FreeCAD Workbench (Phase 5 dry-run)")
    lines.append("import os")
    lines.append("_openems_root = os.environ.get('OPENEMS_INSTALL_DIR', '').strip()")
    lines.append("if _openems_root and hasattr(os, 'add_dll_directory'):")
    lines.append("    os.add_dll_directory(_openems_root)")
    lines.append("import CSXCAD")
    lines.append("import openEMS")
    lines.append("from pathlib import Path")
    lines.append("")
    lines.append("CSX = CSXCAD.ContinuousStructure()")
    x_lines, y_lines, z_lines, delta_unit = _grid_lines_from_model(model)
    lines.append("grid = CSX.GetGrid()")
    lines.append(f"grid.SetDeltaUnit({delta_unit})")
    lines.append(f"grid.AddLine('x', {x_lines})")
    lines.append(f"grid.AddLine('y', {y_lines})")
    lines.append(f"grid.AddLine('z', {z_lines})")
    lines.append("")
    sim = model.simulation or {}
    nr_ts = _as_int(sim.get("NumberOfTimeSteps", 100000), 100000)
    end_criteria = _as_float(sim.get("EndCriteria", 1e-5), 1e-5)
    lines.append(f"FDTD = openEMS.openEMS(NrTS={nr_ts}, EndCriteria={end_criteria})")
    lines.append("FDTD.SetCSX(CSX)")
    excitation_type = str(sim.get("ExcitationType", "Gaussian") or "Gaussian")
    if excitation_type == "Gaussian":
        f0 = _as_float(sim.get("ExcitationF0", 1e9), 1e9)
        fc = _as_float(sim.get("ExcitationFc", 5e8), 5e8)
        lines.append(f"FDTD.SetGaussExcite({f0}, {fc})")
    else:
        lines.append(f"# Unsupported excitation type for Phase 9 MVP: {excitation_type}")
    lines.append("")

    if model.boundary:
        b = model.boundary
        lines.append(
            "FDTD.SetBoundaryCond(["
            f"'{b.get('XMin', 'PEC')}', '{b.get('XMax', 'PEC')}', "
            f"'{b.get('YMin', 'PEC')}', '{b.get('YMax', 'PEC')}', "
            f"'{b.get('ZMin', 'PEC')}', '{b.get('ZMax', 'PEC')}'])"
        )
    lines.append("")

    lines.append("# Materials")
    material_vars: dict[str, str] = {}
    for idx, mat in enumerate(sorted(model.materials, key=lambda item: str(item.get("name", "")))):
        mat_name = str(mat.get("name", f"Material_{idx + 1}") or f"Material_{idx + 1}")
        symbol = f"mat_{idx}_{_safe_symbol(mat_name)}"
        material_vars[mat_name] = symbol

        is_pec = bool(mat.get("IsPEC", False))
        if is_pec:
            lines.append(f"{symbol} = CSX.AddMetal({mat_name!r})")
        else:
            eps = _as_float(mat.get("EpsilonR", 1.0), 1.0)
            mu = _as_float(mat.get("MuR", 1.0), 1.0)
            kappa = _as_float(mat.get("Kappa", 0.0), 0.0)
            lines.append(f"{symbol} = CSX.AddMaterial({mat_name!r})")
            lines.append(
                f"{symbol}.SetMaterialProperty(epsilon={eps}, mue={mu}, kappa={kappa})"
            )
        lines.append(
            f"# MAT {mat_name}: eps={mat.get('EpsilonR')} mu={mat.get('MuR')} "
            f"kappa={mat.get('Kappa')} pec={mat.get('IsPEC')}"
        )
    lines.append("")

    lines.append("# Geometry mapping")
    primitive_geometries = [geo for geo in model.geometries if geo.primitive in {"box", "cylinder"}]

    if primitive_geometries:
        needs_unassigned = any(
            str(getattr(geo, "assigned_material_name", "") or "").strip() not in material_vars
            for geo in primitive_geometries
        )
        if needs_unassigned:
            lines.append("_phase33_unassigned_prop = CSX.AddMaterial('_phase33_unassigned')")
            lines.append("_phase33_unassigned_prop.SetMaterialProperty(epsilon=1.0, mue=1.0, kappa=0.0)")

    for geo in sorted(model.geometries, key=lambda item: item.object_name):
        if geo.primitive == "box":
            start = _vec3(geo.params.get("start"), [0.0, 0.0, 0.0])
            stop = _vec3(geo.params.get("stop"), [1.0, 1.0, 1.0])
            material_name = str(getattr(geo, "assigned_material_name", "") or "").strip()
            prop_var = material_vars.get(material_name, "_phase33_unassigned_prop")
            priority = _as_int(getattr(geo, "assignment_priority", 0), 0)
            lines.append(f"{prop_var}.AddBox({start}, {stop}, priority={priority})")
            lines.append(
                f"# BOX {geo.object_name}: start={start} stop={stop}"
            )
        elif geo.primitive == "cylinder":
            base = _vec3(geo.params.get("base"), [0.0, 0.0, 0.0])
            radius = _as_float(geo.params.get("radius"), 1.0)
            height = _as_float(geo.params.get("height"), 1.0)
            top = [base[0], base[1], base[2] + height]
            material_name = str(getattr(geo, "assigned_material_name", "") or "").strip()
            prop_var = material_vars.get(material_name, "_phase33_unassigned_prop")
            priority = _as_int(getattr(geo, "assignment_priority", 0), 0)
            lines.append(f"{prop_var}.AddCylinder({base}, {top}, {radius}, priority={priority})")
            lines.append(
                f"# CYLINDER {geo.object_name}: base={base} r={radius} h={height}"
            )
        elif geo.primitive == "polyhedron":
            lines.append(
                f"# POLYHEDRON {geo.object_name}: stl={geo.params['stl_path']}"
            )
    lines.append("")

    lines.append("# Ports")
    for port in model.ports:
        lines.append(
            f"# PORT {port.get('name')}: type={port.get('PortType')} "
            f"num={port.get('PortNumber')} R={port.get('Resistance')}"
        )
        if str(port.get("PortType", "")).strip() == "Lumped":
            number = _as_int(port.get("PortNumber", 1), 1)
            resistance = _as_float(port.get("Resistance", 50.0), 50.0)
            excite = 1.0 if bool(port.get("Excite", False)) else 0.0
            direction, reverse = _normalize_direction(port.get("PropagationDirection"))
            start = [
                _as_float(port.get("PortStartX", 0.0), 0.0),
                _as_float(port.get("PortStartY", 0.0), 0.0),
                _as_float(port.get("PortStartZ", 0.0), 0.0),
            ]
            stop = [
                _as_float(port.get("PortStopX", 1.0), 1.0),
                _as_float(port.get("PortStopY", 0.0), 0.0),
                _as_float(port.get("PortStopZ", 0.0), 0.0),
            ]
            if reverse:
                start, stop = stop, start
            lines.append(
                f"port_{number} = FDTD.AddLumpedPort({number}, {resistance}, {start}, {stop}, '{direction}', {excite})"
            )
    lines.append("")

    lines.append("# Dump boxes")
    for dump in model.dumpboxes:
        lines.append(
            f"# DUMP {dump.get('name')}: type={dump.get('DumpType')} freq={dump.get('FrequencySpec')}"
        )
    lines.append("")

    if runnable:
        output_dir = Path(run_output_dir) if run_output_dir else Path("./run")
        lines.append(f"sim_path = Path({str(output_dir)!r})")
        lines.append("sim_path.mkdir(parents=True, exist_ok=True)")
        lines.append("FDTD.Run(str(sim_path), verbose=3)")
        lines.append("print(f'openEMS run completed: {sim_path}')")
    else:
        lines.append("# Dry-run export script generated successfully")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
